export const initialValuesNewUser = {
  identity_card: "",
  names: "",  
  last_names: "", 
  is_foreign: false,
  email: "", 
  phone: "", 
  gender_id: null,
  state_id: null,
  municipality_id: null,
  parish_id: null,
  department_id: null,
  role_id: null,
  username: "",
  password: "",
  passwordRepeat: "",
  address:"",
};
