export const initialValuesNewUser = {
  first_name: "", 
  other_names: "", 
  first_last_name: "",
  other_last_names: "", 
  identity_card: "",
  is_foreign: false,
  email: "", 
  phone: "", 
  gender_id: null,
  state_id: null,
  municipality_id: null,
  parish_id: null,
  department_id: null,
  role_id: null,
  username: "",
  password: "",
  passwordRepeat: "",
  address:"",
};
