export const initialValuesNewUser = {
  first_name: "", 
  other_names: "segundo nombre", 
  first_last_name: "",
  other_last_names: "segundo apellido", 
  identity_card: "",
  is_foreign: false,
  email: "", 
  phone: "", 
  gender_id: null,
  userPhoneNumber2: "",
  stateLocation: "",
  municipalityLocation: "",
  parishLocation: "",
  userOffice: "",
  userRol: "",
  userName: "",
  userPassword: "",
  userPasswordRepeat: "",
};
