export const initialValuesOAC = {
  typeIdOfVictim: "",
  victimIdDocument: "",
  victimName: "",
  victimLastName: "",
  victimPhoneNumber: "",
  victimPhoneNumber2: "",
  victimBirthdate: "",
  gender: "",
  stateLocation: null,
  townShipLocation: null,
  parishLocation: null,
  localLocation: "",
  isPregnant: "",
  numberOfChildren: "",
  ethnicity: "",
  maritalStatus: "",
  levelOfInstruction: "",
  ocupation: "",
}