export const initialValuesNewUser = {
    userFirstName : "",
    userLastName : "",
    userId : "",
    userPhoneNumber : " ",
    userEmail: " ",
    userStateLocation: " ",
    userTownShipLocation: " ",
    userParishLocation:" ",
    userGender : "",
    userOffice: "",
    userRol: "",
    userName: "",
    userPassword:"",
    userPasswordRepeat:"",
}