export const initialValuesNewUser = {
    userFirstName : "",
    userLastName : "",
    userId : "",
    userPhoneNumber : " ",
    userEmail: " ",
    stateLocation: " ",
    municipalityLocation: " ",
    parishLocation:" ",
    userGender : "",
    userOffice: "",
    userRol: "",
    userName: "",
    userPassword:"",
    userPasswordRepeat:"",
}